export const FUTSAL_DETAILS_EDIT_REQUEST = "FUTSAL_DETAILS_EDIT_REQUEST";
export const FUTSAL_DETAILS_EDIT_SUCCESS = "FUTSAL_DETAILS_EDIT_SUCCESS";
export const FUTSAL_DETAILS_EDIT_FAIL = "FUTSAL_DETAILS_EDIT_FAIL";
